$mod = ALT

monitor = , preferred, auto, 1

exec-once = bash -lc 'hyprpaper & sleep 1; hyprctl hyprpaper wallpaper "eDP-1,/home/nukkua/wallpapers/goat_extended.jpg"'
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE


input {
    kb_layout = us
    repeat_rate = 40
    repeat_delay = 250
    follow_mouse = 1
    touchpad {
        natural_scroll = false
        scroll_factor = 2.0
    }
}

general {
    gaps_in = 1
    gaps_out = 1
    border_size = 0
    col.active_border = rgb(c0cbff)
    col.inactive_border = rgb(555555)
    layout = master
}

master {
    mfact = 0.60
    new_status = slave
    new_on_top = false
}

decoration {
    rounding = 0
    shadow {
        enabled = false
    }
}

animations {
    enabled = true
    bezier = smooth, 0.25, 0.9, 0.25, 1.0
    animation = windows, 0
    animation = windowsOut, 0
    animation = fade, 1, 1.5, smooth
    animation = workspaces, 1, 1.5, smooth, fade
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
}

windowrule = match:class brave-origin, workspace 1

bind = $mod, Return, exec, bash -lc 'if [ "$(hyprctl activeworkspace | awk "/windows:/{print \$2; exit}")" = 0 ]; then kitty --start-as fullscreen; else kitty; fi'
bind = $mod, U, exec, shutdown now
bind = $mod, Y, exec, brave-origin --remote-debugging-port=9222 --force-device-scale-factor=1.27
bind = $mod, D, exec, discord --enable-features=UseOzonePlatform --ozone-platform=wayland
bind = $mod, O, exec, bash -lc 'mkdir -p ~/Pictures/Screenshots; f="$HOME/Pictures/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png"; g=$(slurp) || exit; grim -g "$g" "$f" && wl-copy -t image/png < "$f" && notify-send "Screenshot saved" "$f"'
bind = , Print, exec, bash -lc 'mkdir -p ~/Pictures/Screenshots; f="$HOME/Pictures/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png"; g=$(slurp) || exit; grim -g "$g" "$f" && wl-copy -t image/png < "$f" && notify-send "Screenshot saved" "$f"'

bind = $mod, A, exec, kitty --start-as fullscreen -e bash -lc $HOME/scripts/personal.sh
bind = $mod, E, exec, kitty --start-as fullscreen -e bash -lc $HOME/scripts/work.sh
bind = $mod, I, exec, kitty --start-as fullscreen -e bash -lc $HOME/scripts/pdf_searcher.sh
bind = $mod, B, exec, rofi -show drun -theme /home/nukkua/.config/rofi/sakura.rasi
bind = $mod, C, exec, bash -lc "$HOME/.config/fuzzel/web.sh"
bind = $mod CTRL ,C , exec, bash -lc "$HOME/.config/fuzzel/web.sh --tabs-only"
bind = $mod, P, exec, kitty -e pulsemixer

bind = $mod, minus, exec, brightnessctl set 10%-
bind = $mod, M, exec, brightnessctl set 10%+

bind = CTRL, M, exec, amixer -q set Master toggle
bind = CTRL, up, exec, amixer -q set Master 5%+ unmute
bind = CTRL, down, exec, amixer -q set Master 5%- unmute

bind = $mod, Q, killactive
bind = $mod SHIFT, E, exit

bind = $mod, J, cyclenext
bind = $mod, K, cyclenext, prev
bind = $mod SHIFT, J, swapnext
bind = $mod SHIFT, K, swapnext, prev

bind = $mod, comma, focusmonitor, -1
bind = $mod, period, focusmonitor, +1
bind = $mod SHIFT, comma, movewindow, mon:-1
bind = $mod SHIFT, period, movewindow, mon:+1

bind = $mod, L, resizeactive, 20 0
bind = $mod, H, resizeactive, -20 0

bind = $mod SHIFT, space, togglefloating
bind = $mod, F, fullscreen
bind = $mod, X, exec, hyprctl reload


bind = $mod, S, workspace, 1
bind = $mod CTRL, S, movetoworkspace, 1
bind = $mod, N, workspace, 2
bind = $mod CTRL, N, movetoworkspace, 2
bind = $mod, T, workspace, 3
bind = $mod CTRL, T, movetoworkspace, 3
bind = $mod, R, workspace, 4
bind = $mod CTRL, R, movetoworkspace, 4
bind = $mod, W, workspace, 5
bind = $mod SHIFT, W, movetoworkspace, 5
bind = $mod, 6, workspace, 6
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod, 7, workspace, 7
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod, 8, workspace, 8
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod, 9, workspace, 9
bind = $mod SHIFT, 9, movetoworkspace, 9
