# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Aliases
alias ls='ls --color=auto'
LS_COLORS="di=1;38;5;218:fi=0"
export LS_COLORS
alias grep='grep --color=auto'
alias vim='nvim'
alias wmqttx='nohup flatpak run com.emqx.MQTTX &> /dev/null &'
alias sortty='python3 /usr/local/bin/sortty-bin/sortty.py'

# Starship
eval "$(starship init bash)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml

export PATH="$PATH:/usr/bin:/home/leverna/.cargo/bin:/home/leverna/.local/bin:$HOME/flutter/flutter/bin:/home/leverna/.config/composer/vendor/bin:~/go/bin:/opt/cuda/bin:/home/leverna/RegRipper3.0:"

# Condicionales para entornos específicos
if [ -d "$HOME/flutter/flutter/bin" ]; then
    export PATH="$PATH:$HOME/flutter/flutter/bin"
fi

if [ -f "$HOME/.cargo/env" ]; then
    . "$HOME/.cargo/env"
fi

# CUDA settings
export LD_LIBRARY_PATH=/opt/cuda/lib64:$LD_LIBRARY_PATH


LLDB_USE_NATIVE_PDB_READER="yes"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH=$BUN_INSTALL/bin:$PATH
export PATH="/home/leverna/.config/herd-lite/bin:$PATH"
export PHP_INI_SCAN_DIR="/home/leverna/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"
